name: beacon
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  date_time_picker: ^2.0.0
  duration_picker: ^1.1.0+1
  flutter:
    sdk: flutter
  flutter_animarker: ^3.2.0
  flutter_config: ^2.0.0
  flutter_countdown_timer: ^4.1.0
  flutter_local_notifications: ^9.2.0
  flutter_polyline_points: ^1.0.0
  fluttertoast: ^8.0.3
  data_connection_checker: ^0.3.4
  geocoder:
    git:
      url: https://github.com/nguyenxdat/flutter_geocoder.git
      ref: 443b875d8ec80ce525cc6e8f17dfbbbbe7fa3028
  geolocator: ^7.0.1
  get_it: ^7.2.0
  google_maps_flutter: ^2.0.6
  graphql_flutter: ^5.0.0
  hive: ^2.0.4
  intl: ^0.17.0
  location: ^4.3.0
  modal_progress_hud: ^0.1.3
  overlay_support: ^1.2.1
  path_provider: ^2.0.8
  provider: ^6.0.2
  rxdart: ^0.26.0
  share_plus: ^3.0.4
  shared_preferences: ^2.0.6
  sizer: ^2.0.15
  skeleton_text: ^1.0.0
  sliding_up_panel: ^2.0.0+1
  uni_links: ^0.5.1

dev_dependencies:
  build_runner: ^2.0.4
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  test: ^1.14.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: FuturaBold
      fonts:
        - asset: fonts/futura_bold.otf
