name: beacon
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  connectivity_plus: ^2.1.0
  cupertino_icons: ^1.0.5
  date_time_picker: ^2.1.0
  duration_picker: ^1.1.1
  flutter:
    sdk: flutter
  flutter_animarker: ^3.2.0
  flutter_config: ^2.0.2
  flutter_countdown_timer: ^4.1.0
  flutter_local_notifications: ^16.3.0
  flutter_polyline_points: ^1.0.0
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  geolocator: ^10.1.0
  get_it: ^7.6.4 
  google_maps_flutter: ^2.5.3
  graphql_flutter: ^5.1.0
  hive: ^2.2.3
  intl: ^0.17.0
  location: ^4.4.0
  mockito: 
  modal_progress_hud_nsn: ^0.3.0 
  overlay_support: ^2.1.0 
  path_provider: ^2.0.4 
  provider: ^6.1.1
  rxdart: ^0.27.7
  share_plus: ^7.2.1
  shared_preferences: ^2.0.7 
  sizer: ^2.0.15
  skeleton_text: ^3.0.1
  sliding_up_panel: ^2.0.0+1
  uni_links: ^0.5.1
  data_connection_checker_nulls: ^0.0.2
  flutter_geocoder_alternative: any

  # for routing
  auto_route: ^8.1.1


  # for state management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5






dev_dependencies:
  build_runner: ^2.1.2 
  flutter_launcher_icons: ^0.9.3 
  flutter_test:
    sdk: flutter
  hive_generator: 
  test: ^1.16.5 

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: FuturaBold
      fonts:
        - asset: fonts/futura_bold.otf
